language: "node_js"
os: "trusty"
cache: "yarn"
node_js:
  - "node"

stages:
  - "compile"
  - "test"
  - name: "deploy"
    if: "(branch = release) AND (repo = Cromefire/preact-mwc-styled)"

jobs:
  include:
    - stage: "compile"
      script: "yarn build"

    - stage: "test"
      script: "./test.sh"

    - stage: "deploy"
      script: "skip"
      deploy:
        skip_cleanup: true
        provider: "npm"
        email: "cromefirehd@gmail.com"
        api_key:
          secure: "gWzOuIIsol+6ip0fZTQf5v611QafQCoe0SEGOO/SJoBRly7JwSLHXlzOe8zhI6VyXmMRFpPVmzQPsCXTxabhkC8gP2SQL0kcLhNPfCGrCcWUzZ+1WuE1LHYDC9yaFvm2ik895dHBpf2NTjtnZ1CAiywYtbDMfV4o9L6dgVn2jKFdta6WQ+vSJ9cH0DvOWoqqnppdaNAfbYmQA6Y9fqmc5I2kaYpNRQfj+v36/B0LCPmySCTpOXjzBEXfml2GcnRvwUd27LZmKIVw1kFWQJCIORzvyoW1A/bhFOW/093qlz9fkMm64TLGibIERbJJ1kE7WXBvuUN2ybaYFIuZ0A+kIEDoJQDG2zHhc3Ay6TF9J47R4Y2U+2Do3SFS+ibhfOdfeLkZWfGKxokwvjCull+UHUfX13yHm1JYMFh/RacUx21/xdC0PV8LpuG4dxmoQYzf+klVe2tjv3HM8IJDiXxbt5IN2NV3BoaUCc0HWWVW5SvTvmIlQs43+Uz1ceRo/Hpq2CsXwFXqcTGA8ziW61oaBUNComiS1I8RjURY+wEe0dSEQDHMpZGuq1G3Qb2DEywDhhBXOTxwILqHszdCSX/HKqAsnVhkm9tLtQLLwfKg/mgjYRNvQUMLQ5IhZNgayq4pvaPeuwgC0uTvT76mO4iCYE3uDcXMcPtvLUx2xvqLbuw="
        on:
          repo: "Cromefire/preact-mwc-styled"
          branch: "release"
