language: "node_js"
os: "trusty"
cache: "yarn"
node_js:
  - "node"

stages:
  - "compile"
  - "test"
  - name: "deploy"
    if: "(branch = release) AND (repo = Cromefire/preact-mwc-styled)"

jobs:
  include:
    - stage: "compile"
      script: "yarn build"

    - stage: "test"
      script: "./test.sh"

    - stage: "deploy"
      script: "skip"
      deploy:
        skip_cleanup: true
        provider: "npm"
        email: "tim.l@nghorst.net"
        api_key:
          secure: "DkaMM342VXfrSfjZ2Fm5DCu2ZRNq0L0JTSbd6I6exOVcdnA56Tfbu5eEhbaUYkQA6sAP5wAYhRN5uG8DIYNpufJBsYuTxSw15paf/exSN4W2kKjkdpRA4JITgHhOlWkbNmC3i6U0Hxyv5myykDTAGJffF3IzGk8s/7wIb/sGF9PGPtuKxLy7XWzjyEP0kARuS8sfagWAkj0fI5BQ6dXbCYF1CtE7qezz0UzVXnZm2apZudU1gUNGepiTkF5rPfEBFfLK+Z0Uk4XXIwuIh+F4a3G6BEfiRynyibzNmT6C37pGZ0b7rrojv2vCvjUYuqz/gWNneJLjUOYNthtw4lBfMo3b4lOCJStVuysYr5+vd0VrJkiWjR6OLPsVvEnHBpQA0Nd4cK3yElon9vHt5nH+noF+B9+u+0mXYXd2ip5w4q7zGL+Eaeg8gC9AZsTYNEpvjKElMb6e1S0LGNSbyE0bnWWhTbYMA5cJtpbjNL/WZzYdgIv2QTtQRMN4qrGjb+/cfeglXAW+5D0BsHowFmJFB948meq2Xpwaa79EWmAucpNKdKPjoYl+dJ55XxNIdFAars4Jq4jMUiz/AJSXcbMJgWnZpJa4ueDbCellHKAj7Z3GHvw/izcyvR36CZRygorSnFqogCshQrzQud1qawOaaMbIWLUU8vg2tvxQVUOuvJM="
        on:
          repo: "Cromefire/preact-mwc-styled"
          branch: "release"
